9 задание. Абрамов
binomay/java-filmorate pull request #1
Opened 2022-09-27 13:32 UTC by binomay

Финальное задание. Проект № 9

2022-09-28 13:10 UTC, NikolaiDem requested changes

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(minReleaseDate)) {
Релизную дата на null тоже можно проверить.

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +@ResponseStatus(value = HttpStatus.INTERNAL_SERVER_ERROR)
Скорее подойдет BAD_REQUEST.

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +import org.springframework.web.bind.annotation.ResponseStatus;
Кодстайл : отсутствие расстояния между импортами и классом.

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User UpdateUser(@Valid @RequestBody User user) {
updateUser(...)

2022-09-28 13:10 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +
Для проверки поднятия контекста добавить @SpringBootTest
 и сделать пустой тестовый метод.

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/common/Numerator.java
> +public class Numerator {
(Optional) 
У идеального класса следуя Single Responsibility должна быть ровно одна причина для его изменения, а здесь их уже 2.

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkFilm(Film film) {
(Optional)
Лучше делать валидацию одним способом: или через аннотации или через методы валидации. Для проверок, не представленных в стандартных аннотациях, можно создавать собственные аннотации. Аналогично для UserController.

2022-09-28 13:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if(user.getName() == null) {
Имя может быть "".

2022-09-28 13:10 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    //@Autowired
Комментарии излишни.

2022-09-28 13:10 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
> +    //@Autowired
Комментарии излишни.

2022-09-28 13:10 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +public class FilmControllerTest {
Для тестов лучше также проверить и сообщение об ошибке.
Аналогично для UserControllerTest.

2022-09-29 13:39 UTC, binomay commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkFilm(Film film) {
Проговаривали с наставником: элементарные вещи (@NotNull и т.д.) можно делать через аннотации, что чуть более сложно (где есть логика), то лучше делать отдельные методы, иначе запаришься отлаживаться.... я с ним согласен полностью. В связи с тем, что замечание Optional - не дорабатываю

2022-09-30 19:48 UTC, NikolaiDem approved these changes

2025-08-08 02:10 UTC, merged