Add friends likes
binomay/java-filmorate pull request #2
Opened 2022-10-06 11:55 UTC by binomay

Add friends likes

2022-10-07 00:43 UTC, NikolaiDem requested changes

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ResponseBody
@ResponseBody в методах RestController-а избыточно. Аналогично для getCommonFriends(...)

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    //TODO: добавил
TODO?

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Optional<Film> optFilm = storage.getFilmById(filmId);
(Optional)
        return storage.getFilmById(filmId)
            .orElseThrow(() -> {
                String msg = "Не могу найти фильм с Id =" + filmId;
                log.warn(msg);
                throw new ResourceNotFoundException(msg);
            });

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        Optional<User> optUser = storage.getUserById(userId);
return storage.getUserById(userId)
            .orElseThrow(() -> {
                String msg = "Не нашел пользователя с Id = " + userId;
                log.warn(msg);
                throw new ResourceNotFoundException(msg);
            });

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        return list1.stream().filter(u -> list2.contains(u)).collect(Collectors.toList());
Использование списка друзей пользователя в виде Set-а, а не List-а будет работать быстрее при использовании contains(...)

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Builder
Не используется.

2022-10-07 00:43 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Остальные тесты потерялись.

2022-10-07 00:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private TreeSet<Film> prioritizedFilmsByLikes = new TreeSet<>(new FilmComparatorByLikes());
Можно не добавлять дублирующую коллекцию.

2022-10-10 07:24 UTC, binomay commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Все тестирование контроллеров покрывается тестами PostMan

2022-10-10 07:28 UTC, closed without merging