Add database
binomay/java-filmorate pull request #5
Opened 2022-11-27 13:44 UTC by binomay

2022-11-28 18:47 UTC, NikolaiDem requested changes

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +
Удалить неиспользуемые импорты и закомментированные строки.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +
Удалить неиспользуемые импорты и закомментированные строки.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Удалить неиспользуемые импорты и закомментированные строки.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    //@NotNull
Почему NotNull удалено?

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setGenre(Genre genre){
Методы setGenre(...) и setLike(...) все же не устанавливают, а добавляют лайки (переименовать в add...)

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Film oldFilm = getFilmById(film.getId());
Не используется, а проверка есть в строке 43.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        return storage.getPrioritizedFilmList().stream().limit(countFilms).collect(Collectors.toList());
Чтобы из БД не извлекать лишние данные, можно сделать limit на уровне БД.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +    public List<Genre> getAllGenres() throws SQLException {
SQLException не будет брошено, можно удалить.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/rating/RatingService.java
> +    public List<Rating> getAllRatings() throws SQLException {
SQLException не будет брошено, можно удалить.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        return set1.stream().filter(u -> set2.contains(u)).map(u -> getUserById(u)).collect(Collectors.toList());
Найти пересечение друзей можно на уровне БД через джойны.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        String sql = "SELECT F.*  FROM FILMS F LEFT OUTER JOIN FILMLIKES Fl on FL.FILM_ID = F.ID" +
Так как у фильма есть поле rate, которое представляет собой количество лайков, то достаточно при поиске самых популярных фильмов отсортировать по этому полю.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +public class DBFilmStorage implements FilmStorage {
Удалить закомментированные строки.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +    public void addLikeToFilm(Film film, User user) {
При добавлении и удалении лайка нужно обновлять поле rate у фильма.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        for (Integer user_id : likeIdList) {
userId

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        for (Genre genre : film.getGenres()) {
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        film.setMpa(ratingStorage.getRatingById(mpaId).get());
При выборе фильмов можно сделать джойн к RATING и без дополнительного запроса получить rating.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        List<Film> filmList = jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
Здесь возникает проблема "N+1 query". Одним запросом получены все N фильмов, и для каждого фильма нужно сделать еще по одному запросу (на самом деле по 3 : setMpa(), setAllGenresToFilm(), setAllLikesToFilm()) то есть дополнительных N запросов. Поэтому получать лайки и жанры лучше тоже одним запросом.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DBUserStorage.java
> +        String sql = "SELECT * FROM FRIENDSHIP WHERE USER_ID = " + user.getId();
Почему не учитывается статус дружбы ACCEPTED?

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DBUserStorage.java
> +            addAllFriendsToUser(user);
Здесь тоже проблема N + 1 запроса. Друзей можно вытащить в одном запросе.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +
Удалить пустые строки.

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/resources/data.sql
> +--ПОДЧИСТИМ, ИНАЧЕ ПОСТМАН НЕ ПРХОДИТ
Зачем удалять все данные, какие ошибки?

2022-11-28 18:47 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +create table IF NOT EXISTS FILMLIKES
Для таблиц FILMLIKES, FRIENDSHIP и FILMGENRE поле id выглядит избыточным.

2022-11-28 20:56 UTC, binomay commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +    public List<Genre> getAllGenres() throws SQLException {
Если удалить, тогда ошибка при компиляции:
C:\Users\Andrey\dev\java-filmorate\src\main\java\ru\yandex\practicum\filmorate\service\genre\GenreService.java:32:36
java: unreported exception java.sql.SQLException; must be caught or declared to be thrown

2022-11-28 21:00 UTC, binomay commented on src/main/java/ru/yandex/practicum/filmorate/service/rating/RatingService.java
> +    public List<Rating> getAllRatings() throws SQLException {
если убрать, тогда ошибка при компиляции:
java: unreported exception java.sql.SQLException; must be caught or declared to be thrown

2022-12-01 10:16 UTC, NikolaiDem requested changes

2022-12-01 10:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DBUserStorage.java
> +                friend.addFriend(friend);
Для добавления в друзья можно не создавать новый объект, достаточно знать id.

2022-12-01 10:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        Дилемма: либо тащим только фильмы и ограничиваем выборку в запросе (limit MaxCountFilm),
Можно вытащить сначала все фильмы с лимитом (без жанров и лайков). А потом сделать 2 запроса : один для получения лайков, а другой для жанров всех фильмов. Тогда проблемы N+1 не будет.

2022-12-01 10:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +        return "SELECT F.ID FILM_ID, "
(Optional)
Можно использовать F.* вместо явного обозначения всех полей

2022-12-01 10:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/rating/RatingService.java
> +    public List<Rating> getAllRatings() throws SQLException {
В storage соответственно тоже удалить SQLException

2022-12-01 10:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +    public List<Genre> getAllGenres() throws SQLException {
В storage соответственно тоже удалить SQLException

2022-12-01 15:17 UTC, NikolaiDem approved these changes

2022-12-01 15:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +    private final GenreStorage genreStorage;
Не используется

2022-12-01 15:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +            sql = sql + film.getId() + ", ";
Не самый оптимальный способ соединения строк)

2022-12-01 15:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/DBFilmStorage.java
> +    private List<Integer> getLikeList(Film film) {
Не используется

2022-12-01 15:17 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/DBUserStorage.java
> +    private User makeFriend(SqlRowSet rs) {
Не используется

2025-08-08 02:10 UTC, merged